article_links = [
    'https://www.udmurt.ru/press_center/news/glazovskiy-zavod-metalloizdeliy-uvelichil-effektivnost-proizvodstva-na-15/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/udmurtiya-vnov-sredi-liderov-po-realizatsii-natsionalnogo-proekta-proizvoditelnost-truda/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/novaya-mebelnaya-fabrika-prodolzhaet-vnedryat-berezhlivye-tekhnologii-na-vsekh-proizvodstvennykh-uch/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/izhevskiy-proizvoditel-gidravlicheskogo-oborudovaniya-prisoedinilsya-k-uchastiyu-v-natsionalnom-proe/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/komanda-izhvodokanala-vzyala-kubok-mezhdunarodnogo-chempionata-po-ratsionalizatsii-i-proizvoditelnos/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/izhevskiy-proizvoditel-neftegazovogo-oborudovaniya-prisoedinilsya-k-natsproektu-proizvoditelnost-tru/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/regionalnyy-tsentr-kompetentsiy-v-sfere-proizvoditelnosti-truda-po-udmurtii-proshel-sertifikatsiyu-f/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/na-8-5-protsentov-uvelichilas-proizvoditelnost-truda-na-glazovskom-zavode-remmash/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/gruppa-kompaniy-rogos-vstupila-v-natsproekt-proizvoditelnost-truda-/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/na-14-uvelichitsya-vyrabotka-na-predpriyatii-udmurtagrokhim-blagodarya-natsproektu-proizvoditelnost-/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/glazovskiy-forvard-mebel-planiruet-uskorit-sborku-produktsii-v-2-raza/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/sarapulskiy-elektromekhanicheskiy-zavod-uvelichil-kolichestvo-sobiraemykh-transformatornykh-podstants/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/promyshlennyy-forum-otkroetsya-v-izhevske-v-den-oruzheynika-rossii-/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/kak-opyt-farmkompanii-mozhet-pomoch-pomoch-proizvoditelyu-elektrotekhnicheskogo-oborudovaniya/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/v-moskve-na-federalnom-konkurse-po-natsproektu-elekond-voshel-v-troyku-pobediteley/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/predpriyatiya-uchastniki-natsionalnogo-proekta-proizvoditelnost-truda-v-udmurtii-uvelichili-vyruchku/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/v-udmurtii-bolee-500-rabotnikov-predpriyatiy-obuchilis-optimizatsii-ofisnykh-protsessov-v-ramkakh-na/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/na-udmurtskom-predpriyatii-pristupili-k-optimizatsii-protsessov-v-ramkakh-natsionalnogo-proekta/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/60-instruktorov-po-berezhlivomu-proizvodstvu-proshli-sertifikatsiyu/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/kak-ergonomika-pomogaet-proizvoditelnosti-truda/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/svoy-trener-po-berezhlivomu-proizvodstvu-mozhet-poyavitsya-na-kazhdom-predpriyatii-udmurtii/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/blagodarya-natsproektu-lekarstvennye-preparaty-znachitelno-bystree-postupayut-k-konechnomu-potrebite/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/natsionalnyy-proekt-proizvoditelnost-truda-na-strazhe-agropromyshlennoy-sfery-regiona/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/udmurtskoe-predpriyatie-kriotekhnika-pristupilo-k-modernizatsii-proizvodstva-v-ramkakh-natsproekta/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/predpriyatie-energoregion-v-dva-raza-uskorilo-vypusk-produktsii-blagodarya-natsproektu/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/uzhe-50-sotrudnikov-kompanii-uva-moloko-poluchili-znaniya-blagodarya-natsproektu-proizvoditelnost-tr/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/instrumenty-natsproekta-pozvolili-predpriyatiyu-udmurtii-naladit-importozameshchenie/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/natsproekt-proizvoditelnost-truda-sekonomil-molodoy-kompanii-iz-udmurtii-uzhe-poryadka-4-mln-rubley/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/v-udmurtii-startovali-pervye-meropriyatiya-natsproekta-proizvoditelnost-truda/?sphrase_id=14771',
    'https://www.udmurt.ru/press_center/news/uchastniki-natsproekta-delyatsya-opytom-so-shveynoy-otraslyu-udmurtii/?sphrase_id=14771',
    ]


answer_links = [
    'вспомни семь видов потерь при подготовке новогоднего стола',
    'что будешь делать на третьем шаге системы 5С третьего января?',
    'как применить основной принцип SMED, когда идешь в гости на новый год?',
    'перечисли в 23.45 все 11 листов стандартизированной работы, осмысли всю их ценность в наступающем году',
    'что делать если показатель производительности OEE оказался 31 декабря выше единицы?',
    'остерегайся балансировки в темных закоулках. Какой инструмент применишь в качестве защиты от злых чар?',
    'что такое каракури и как ее применить при установке елки?',
    'РЦК Удмуртии - лучшие',
    'как перепроизводство влияет на прочностные характеристики новогоднего стола?',
    'разработай кайдзен по нормализации первоянварского состояния',
    'примени ТРИЗ для решения задачи отсутсвия/сокращения мусора от феерверков'
    ]
